### ISSUE TITLE
Persisting settings

### ISSUE THREAD

**Issue by bluenote10** [passcod/cargo-watch#134]
Maybe I'm missing something, but I can't find anything in the documentation on my most important feature: Persisting settings. I need a bunch of ignore patterns, and want to have stuff like `--clear` enabled by default. The command line is getting cumbersome to maintain. Is this not possible without having to write yet another wrapper script on top?

**Comment by passcod** [comment]
There's another tool called [cargo make](https://github.com/sagiegurari/cargo-make) that enables some of this kind of thing, and there is already [support for a `.ignore` file](https://github.com/passcod/cargo-watch#ignore-files) on top of `.gitignore` which may help with the ignore patterns. Otherwise, no, there's no configuration file at the moment, though one is [planned upstream](https://github.com/watchexec/watchexec/issues/33).
