### ISSUE TITLE
Add option to only display the amount of lines a terminal has for each run

### ISSUE THREAD

**Issue by twiclo** [passcod/cargo-watch#165]
I'm always finding myself scrolling to the top of the last ran `cargo run` to start working on errors. I prefer working on first errors first. It would be nice if cargo-watch could just stop outputing once it hits the end of my terminal so I don't have to scroll up.

I would be willing to work on a fork for this if you could give me some guidance on where to start

**Comment by passcod** [comment]
You probably want pager integration? That's what it sounds like. Although I _feel_ like your particular use case is probably better handled by whatever you run...

That said, adding pager support (to watchexec) or some pager functionality is fairly often requested and would be well appreciated I feel.

In the longer term, I'm working on a much more full featured replacement / different take on cargo-watch/watchexec/nodemon/that entire class of programs that would do this natively.

**Comment by twiclo** [comment]
Not sure what you mean by pager. If you mean pagination that's not it. Basically the program should check how tall the terminal window is then only output the same amount of lines. Or maybe a nicer way to only show the first X errors without trying to finagle it into `head`

**Comment by passcod** [comment]
pager. like `less`.

**Comment by twiclo** [comment]
It's true that I only want one page. Seems to me it's easier to stop printing at X lines but if the pager is the way to go that's fine by me. As long as I won't have to interact with it to reload a new run

**Comment by passcod** [comment]
> Or maybe a nicer way to only show the first X errors without trying to finagle it into head

That would be a cargo concern, not a cargo-watch thing.

But yeah you _could_ use e.g. `cargo check | head -n $(tput rows)` or something.

**Comment by twiclo** [comment]
Yes through cargo I could make this program unnecessary but the reason I like it and use it is because it's convenient

**Comment by passcod** [comment]
No, I don't mean _replace_ cargo watch. I mean use this kind of command _with_ cargo watch, with the `-x` or `-s` options.

Fundamentally, the functionality you're looking for can already be done by composing cargo-watch with either a head command or a pager or whatever. Putting it into cargo-watch itself is redundant and would just end up either inflexible or overly complicated. Using a pager through cargo-watch is known to be iffy in some cases, due to how terminals work, and implementing a pager is more work than it seems at first. But you don't need a pager, you just need to use head inside cargo-watch, which you can do right now.

If you have further issues, please describe what you tried and how that doesn't work out.

**Comment by marcospb19** [comment]
(Hey @passcod, thanks for the amazing pieces of software you've built)

I personally think that it would be better for `cargo-watch` to have use a pager by default.

Using `bat` as an example ([code link](https://github.com/sharkdp/bat/blob/master/src/pager.rs)), it does support paging and it makes `bat` so convenient that we don't want or use `cat` or `less` ever again.

![image](https://user-images.githubusercontent.com/38900226/113475699-9948a680-944d-11eb-933d-f9d95c135e9c.png)

The default pager is `less` but the **main point** for _me_ is that it only uses the pager when the output doesn't fit in the screen, and that makes a lot of difference for the user (compared to `less` or `cat` directly).

I don't understand the difficulties involved in making this possible, but scrolling through the output is painful for the majority of `cargo-watch` users, as I don't expect the users to compose `-x` or `-s` options with pagers manually.

**Comment by passcod** [comment]
Yeah, it would be really cool to have it. Though I do think it should be as an option (unless a majority of users say it should be the default). So... implement it, provide a PR, and then we'll have it.

**Comment by passcod** [comment]
Closing in favour of upstream issue.

**Comment by marcospb19** [comment]
(https://github.com/watchexec/watchexec/issues/88)

**Comment by mindreader** [comment]
I've yet to find a command I can pass to cargo watch to make this work in any fashion. None of the following work.

`cargo watch -- sh -c 'cargo run | less'`
`cargo watch -- sh -c 'cargo run 2>&1 | less'`
`cargo watch -s 'cargo run 2>&1 | less'`

**Comment by passcod** [comment]
You're going to have to add environment details or what you mean by "doesn't work" or something because as far as my testing goes `cargo watch -x 'run | less'` works fine. And also what your program is doing, if that's affecting screen rendering.






---- On Tue, 14 Sep 2021 06:27:49 +1200 David McHealy ***@***.***> wrote ----




I've yet to find a command I can pass to cargo watch to make this work in any fashion. None of the following work.

cargo watch -- sh -c 'cargo run | less'
 cargo watch -- sh -c 'cargo run 2>&1 | less'
 cargo watch -s 'cargo run 2>&1 | less'

**Comment by mindreader** [comment]
It didn't capture build output, which was my primary motivation as the first error is the most important 99% of the time. I had to mess with it awhile, but what I found to work is the following.

`cargo watch -s 'cargo --color always run 2>&1 | less -r'`

Explanations:
* `2>&1` - cargo sends its compile output to stderr, less only takes in stdout, this redirects stderr to stdout
* `--color always` - cargo does its compile in stderr, but if you combine stderr and stdout the colors go away unless you force it to keep them
*  `less -r` - the r flag tells less to interpret ansi color codes so that you get the normal colors that cargo would display
