### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by whitequark** [passcod/cargo-watch#58]
Guard can integrate with desktop notification systems (libnotify, growl, etc). Please consider adding this feature to cargo-watch.

[rust-libnotify](https://crumblingstatue.github.io/doc/libnotify/libnotify/index.html) seems reasonably high-quality to me.

**Comment by passcod** [comment]
The problem with rust-libnotify is that it's Linux-only.

**Comment by whitequark** [comment]
Sure, it's only a part of the solution. It looks like there's no Growl library for Rust yet, too.

**Comment by passcod** [comment]
Right, so I'll wait until there's a solution that's reasonably cross-platform, at least supporting Windows and macOS in addition to Linux.

**Comment by whitequark** [comment]
There's no cross-platform solution. On Linux you use libnotify, on macOS and Windows you use Growl. I think this shouldn't be a problem since Cargo allows you to specify platform-specific dependencies.

**Comment by mehcode** [comment]
It'd be neat if there was a `rust-notify` lib that had an API that made that platform choice for me.

**Comment by passcod** [comment]
Right, so, this project is built on Notify, which is a cross-platform solution for filesystem notifications. The _way_ it does that is by platform-specific and fallback solutions. For command handling, we use Duct, which also does platform-specific solutions. But they're both single libraries that cover all that. **In cargo-watch**, I don't want to do the platform-specific-logic myself.

What I'm saying by "I'll wait until there's a solution that's reasonably cross-platform" is that until there's a crate that does this, like @mehcode suggested, I'm not going to add the feature to cargo-watch. That's a project decision :) but I'd love having this feature.

**Comment by whitequark** [comment]
For posterity, here are the 16 lines of code needed to support macOS and Linux: https://github.com/frewsxcv/alert-after/blob/master/main.rs#L8-L24

**Comment by passcod** [comment]
Firstly, as a nitpick, you posted a link referencing _the master branch_, which means when it changes, your "for posterity" will point to the wrong thing.

Secondly, "for posterity", here are the issues tracking Windows/other OS support on that project and the underlying library: https://github.com/frewsxcv/alert-after/issues/2 and https://github.com/hoodie/notify-rust/issues/22 and https://github.com/hoodie/notify-rust/issues/25 and, guess what, 7 hours ago I'd already subscribed to all three of them so that _when Windows and good/better MacOS support lands_ I'd be able to go right ahead and add desktop notifications.

If you think that's too slow, you are very welcome to go and submit a PR to `notify-rust` for Windows support. I will not be doing it myself because a) I don't have a Windows machine to dev on, and b) I have other things to do with higher priority.

**Comment by whitequark** [comment]
I simply put some code references in the issue so that I (or anyone else who wants to work on this) would not have to go look for them again. I have not been expecting a response, and I don't know what's up with this passive-aggressive one.

**Comment by passcod** [comment]
Ah. Well, apologies, I read your comment wrong. Sorry for that.
