### ISSUE TITLE
after update from 4.0.3 to 5.0.4: No space left on device

### ISSUE THREAD

**Issue by chabapok** [passcod/cargo-watch#72]
OS: ubuntu x64 14.04

Аfter update from 4.0.3 to 5.0.4:

> $ cargo watch
> thread 'main' panicked at 'unable to create watcher: Io(Error { repr: Os { code: 28, message: "No space left on device" } })', /checkout/src/libcore/result.rs:859
> note: Run with `RUST_BACKTRACE=1` for a backtrace

And with --poll key: `cargo watch --poll` run ok and works, but consume 100% of cpu.

4.0.3 works ok.

**Comment by hcpl** [comment]
`cargo-watch` switched to wrapping `watchexec` in 5.0.0. Not an owner, but I doubt the problem lies in `cargo-watch` itself.

Does `watchexec` work for you?

**Comment by chabapok** [comment]
The problem is in watchexec (there is 89G free on device):

> $ watchexec -- ls -la
thread 'main' panicked at 'unable to create watcher: Io(Error { repr: Os { code: 28, message: "No space left on device" } })', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Aborted (core dumped)

**Comment by hcpl** [comment]
Try to file this issue to https://github.com/mattgreen/watchexec then.

**Comment by chabapok** [comment]
Ok

**Comment by chabapok** [comment]
`cargo watch --poll --debug` show:

> ... poll: true, poll_interval: 1

As far as i understand, watcher consume 100% CPU, because default poll intervel ==1, but 500...2000 is better for default.

**Comment by passcod** [comment]
Hmm, must have misread the docs when I implemented that, I meant 1 _second_, not millisecond.

**Comment by passcod** [comment]
Also the "no space left on device" is [probably a watcher limit](https://github.com/passcod/cargo-watch#linux-if-it-fails-to-watch-some-deep-directories-but-not-others).

**Comment by passcod** [comment]
(I wrote both cargo watch and **notify**, the library watchexec uses. This is a fairly frequent error.)

**Comment by passcod** [comment]
Both fixed/documented in [5.0.5](https://github.com/passcod/cargo-watch/releases/tag/v5.0.5).

**Comment by hcpl** [comment]
@passcod no problem!

And there are two things I'd like to mention:
- It would be useful to have a FAQ for `notify` too since the root cause is there, move/duplicate some questions regarding low-level details and add a link to it from `cargo-watch`. `watchexec` can also have a FAQ of its own which links to `notify`; in this case `cargo-watch` should mention `watchexec` FAQ too.
- Seems like http://blog.sorah.jp is [down](http://downforeveryoneorjustme.com/http://blog.sorah.jp) for now, so http://blog.sorah.jp/2012/01/24/inotify-limitation always returns "502 Bad Gateway". Fortunately it can be replaced by the most recent Web Archive snapshot (http://web.archive.org/web/20161106193425/http://blog.sorah.jp:80/2012/01/24/inotify-limitation).

**Comment by passcod** [comment]
I'll get onto that, thanks for the feedback :)
