### ISSUE TITLE
`cargo watch -x run -- --data-dir ./data` doesn't work

### ISSUE THREAD

**Issue by dpc** [passcod/cargo-watch#97]
```
> cargo watch -x run -- --data-dir ./data
error: Found argument '--data-dir' which wasn't expected, or isn't valid in this context

USAGE:
    cargo watch [FLAGS] [OPTIONS]

For more information try --help
```

What works is `cargo watch -x "run -- --data-dir ./data"`, but I don't believe it should be necessary.

**Comment by passcod** [comment]
What would you expect `cargo watch -x check -x run -- --data-dir ./data` to do? Out of curiosity, not implying you're wrong in any way

**Comment by dpc** [comment]
The same thing as `cargo watch -x "run -- --data-dir ./data"` does

I guess, in essence, I'm asking to change:

```
cargo watch [FLAGS] [OPTIONS]
[...]
-x, --exec <cmd>...
```

to:


```
cargo watch [FLAGS] [OPTIONS] [CMD...]
[...]
-x, --exec ...
```

It's a typical pattern for commands that execute other command.

Eg.

```
> rustup run stable echo a b c
a b c
```

works just fine and doesn't need `"echo a b c"`. In fact:

```
> rustup run stable "echo a b c"
error: command failed: 'echo a b c'
info: caused by: No such file or directory (os error 2)

**Comment by passcod** [comment]
Yeah, I'm just wondering given how cargo watch can run multiple commands. Would the expectation be entirely that the "rest of the arguments" go to the last-mentioned command?

Also, for shorthand, would it be

    cargo watch run -- --foo bar

with `-x` implied, or should the `-x` or `-s` be required like

    cargo watch -x run -- --gone fishing
    cargo watch -s command -- --and-arg here

Additionally, given `cargo watch [FLAGS] [OPTIONS] [CMD...]`, one might expect this to work:

    cargo watch -x run echo -n foo

yet I'm not super sure a) that this can be done (with clap and how it's used here), nor b) that this should be supported.

It's a good idea, but I want to explore more of the edge cases and expectations.

**Comment by dpc** [comment]
I wasn't aware that many commands can be given. Any combination of commands can be expressed by one shell command.

Eg.

```
cargo watch -s cargo build --release \; cargo test
```

should work just fine. `cargo-watch` will get a command line `cargo build --release ; cargo test` and will pass it to shell, which should do the right thing. (Same as ` rustup run stable echo foo \; echo r` does)


From my perspective, `-x` is just a convenient way to prefix the command with `cargo`.

I'm quite sure `clap` allowed taking all leftover arguments after somehow, so maybe structopt can too.

**Comment by dpc** [comment]
```
#[macro_use]
extern crate structopt;

use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(short = "x")]
    flag: bool,
    cmd: Vec<String>,
}

fn main() {
    let opt = Opt::from_args();
    println!("Hello, {:#?}", opt);
}
```


```
[I] 07-22 15:33 dpc@futex ~/l/b/foo (editor)> cargo run -- bar biz \;
   Compiling foo v0.1.0 (file:///home/dpc/lab/brainwiki/foo)                                                                                                            
    Finished dev [unoptimized + debuginfo] target(s) in 0.58s                                                                                                           
     Running `target/debug/foo bar biz ';'`
Hello, Opt {
    flag: false,
    cmd: [
        "bar",
        "biz",
        ";"
    ]
}
[I] 07-22 15:33 dpc@futex ~/l/b/foo (editor)> cargo run -- -x bar biz \;
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s                                                                                                           
     Running `target/debug/foo -x bar biz ';'`
Hello, Opt {
    flag: true,
    cmd: [
        "bar",
        "biz",
        ";"
    ]
}
```

**Comment by dpc** [comment]
It should really be `cmd: Vec<OsString>,`, but that might require some additional work...

**Comment by dpc** [comment]
Actually:

```
#[macro_use]
extern crate structopt;

use std::ffi::OsString;
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct Opt {
    #[structopt(short = "x")]
    flag: bool,
    #[structopt(parse(from_os_str))]
    cmd: Vec<OsString>,
}

fn main() {
    let opt = Opt::from_args();
    println!("Hello, {:#?}", opt);
}
```

**Comment by passcod** [comment]
Sorry, I wasn't saying I wasn't sure whether your original proposal was possible in clap (we don't use structopts, so as cool as it looks, not relevant except in that whatever it does, clap does too). Rather, consider this:

    cargo watch -s echo -n foo

Here are three equally possible, depending on implementation, ways this could go:

1. "ERROR: `-n` is not an accepted flag"
2. `echo -n foo` being run
3. (at a later stage, assuming `-n` becomes a flag or option to _cargo watch_) `echo foo` being run, and `-n` being passed to cargo watch.

I believe the expectation of a user would be number 2. Number 1 would probably be acceptable, especially if we could detect that particular case somehow and give an additional error message like "looks like you're trying to pass flags to the command, try quoting or using `--` to separate arguments. Number 3 would be very confusing.

What I don't know is whether number 2 would be possible to parse. I suspect not, given that then we'd have ambiguity with this:

    cargo watch -s foo -s bar

Is the command being asked to run `foo` and `bar`, or `foo -s bar`? Can't tell.

Alright, so it would probably be that if `cargo watch -s echo -n bar` we'll do number 1, and an error will be thrown... except if the flag or option being used is one cargo watch supports, in which case number 3 will apply!

We could just say that there's to be no trailing argument accepted of any sort if `--` is not passed. How do we tell that? Does clap tell us or can it do it for us?

That would solve that ambiguity, but I'll bet that at some point someone will try without the `--` and either be surprised to get an error, or hit just the right command that it will _look_ like it worked but instead silently does something odd.

----

Also, yes, `-x` is merely a convenience, and multi-command _could_ be replaced with letting people do their own chaining. For historical and other reasons, mostly that people asked to be able to do that, that's not the case. Removing those features would help in clarifying the situation and avoiding ambiguities in this case, but I'm don't think it's a very good idea to, at least not right now.

I believe I'd need to have a better reason to break the interface, otherwise I'll have people showing up complaining that they upgraded and _suddenly all their workflows died_ and I'd be like "yeah but look, now you can do this particular thing without quotes".

----

To reiterate: I don't think this is a bad idea. Indeed I think this is a good idea, and I'm kicking myself for not thinking about it before.

But I do want to consider all angles of this, not just "is this doable". (It is!)

There's a cost analysis there. Implementation cost is probably very low. Design cost is moderately low: there's some complexities and ambiguities to be worked through. Then I need to consider support cost (what queries and issues will come from this, and how can I prevent most of them at the earliest, preferably design, stage?), and maintainer cost (will this change have implications and restrictions in how cargo watch can evolve in the future?), and user-friendliness cost (will this make the interface harder or easier to grok and in what ways? both can be true at the same time in different ways, too).

**Comment by dpc** [comment]
> Here are three equally possible, depending on implementation, ways this could go:

That's what `--` is for in Unix. :)

Anything after `--` is free-running arguments, and not flags etc.

So:


```
cargo watch -s echo -n foo
```

is 

```
cargo watch -n foo -s echo
```

while:

```
cargo watch -s -- echo -n foo
```

runs `echo -n foo being run`

Note, that according to this proposal, `-s` is a flag and is not taking any arguments, so.


```
cargo watch -n foo -s echo
```

and

```
cargo watch -s -n foo echo
```

are effective the same, and `-s` means just "the free-running arguments are to be interpreted as shell command".

**Comment by dpc** [comment]
>  and user-friendliness cost 

Note: it's not even my idea. It's Unix tradition or something and I am just used to Unix tools working this way.

Anyway, I just wanted to bring it to your attention, and it's not a big deal one way or another.

**Comment by kpcyrd** [comment]
I just tried it and I think it's implemented incorrectly:
```
% cargo watch -- cargo check
[Running 'cargo']
Rust's package manager

USAGE:
    cargo [+toolchain] [OPTIONS] [SUBCOMMAND]

OPTIONS:
    -V, --version                  Print version info and exit
        --list                     List installed commands
        --explain <CODE>           Run `rustc --explain CODE`
    -v, --verbose                  Use verbose output (-vv very verbose/build.rs output)
    -q, --quiet                    No output printed to stdout
        --color <WHEN>             Coloring: auto, always, never
        --frozen                   Require Cargo.lock and cache are up to date
        --locked                   Require Cargo.lock is up to date
        --offline                  Run without accessing the network
        --config <KEY=VALUE>...    Override a configuration value (unstable)
    -Z <FLAG>...                   Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
    -h, --help                     Prints help information

Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the target directory
    doc         Build this package's and its dependencies' documentation
    new         Create a new cargo package
    init        Create a new cargo package in an existing directory
    run, r      Run a binary or example of the local package
    test, t     Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Package and upload this package to the registry
    install     Install a Rust binary. Default location is $HOME/.cargo/bin
    uninstall   Uninstall a Rust binary

See 'cargo help <command>' for more information on a specific command.
[Finished running. Exit status: 0]
^C
```
It seems it's only using the first argument and passing it to `sh -c`, so there's no real difference to `-s` :)
```
 cargo watch -- 'cargo check'
[Running 'cargo check']
    Blocking waiting for file lock on build directory
^C
```
